/* tslint:disable */
/* eslint-disable */
/**
 * FixNa- OpenAPI 3.0
 * OpenAPI specification for FixNa
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: gervasius@logicpp.com.na
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";
export * from "./models";
