/* tslint:disable */
/* eslint-disable */
/**
 * FixNa- OpenAPI 3.0
 * OpenAPI specification for FixNa
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: gervasius@logicpp.com.na
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Issue
 */
export interface Issue {
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    'issue_id': string;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    'date': string;
    /**
     * 
     * @type {number}
     * @memberof Issue
     */
    'latitude': number;
    /**
     * 
     * @type {number}
     * @memberof Issue
     */
    'longitude': number;
}

