version: "3.8"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "fixna"
      MYSQL_ROOT_PASSWORD: "admin@FixNa9"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    # volumes:
    #   - ./db:/var/lib/mysql
